"""esquema inicial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-10 07:48:02.946452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de la revisión, usados por Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('area_conocimiento', sa.String(length=100), nullable=False),
    sa.Column('nivel_formacion', sa.Enum('tecnico', 'tecnologo', 'universitario', 'posgrado', name='nivel_formacion_enum'), nullable=False),
    sa.Column('modalidad', sa.Enum('presencial', 'remoto', 'hibrido', name='modalidad_enum'), nullable=False),
    sa.Column('disponibilidad_horaria', sa.Enum('tiempo_completo', 'medio_tiempo', 'fines_de_semana', 'flexible', name='disponibilidad_horaria_enum'), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('salario_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vacantes_disponibles', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'publicada', 'cerrada', 'cubierta', name='estado_vacante_enum'), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacantes_area_conocimiento'), 'vacantes', ['area_conocimiento'], unique=False)
    op.create_index(op.f('ix_vacantes_empresa_id'), 'vacantes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_vacantes_estado'), 'vacantes', ['estado'], unique=False)
    op.create_table('documentos_vacante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacante_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisitos_vacante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacante_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisitos_vacante')
    op.drop_table('documentos_vacante')
    op.drop_index(op.f('ix_vacantes_estado'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_empresa_id'), table_name='vacantes')
    op.drop_index(op.f('ix_vacantes_area_conocimiento'), table_name='vacantes')
    op.drop_table('vacantes')
    # ### end Alembic commands ###
